route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'k.mooijman@gmail.com'
        auth_password: "Vila Nova de Milfontes 7523"
        from: 'k.mooijman@gmail.com'
        to: 'kasper@mooijman.info'
