{
 "title": "Kaspertest",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Local Machine Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) expport_dashboard.sh grafana_dashboards 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processor Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) expport_dashboard.sh grafana_dashboards 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Machine Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Percentage Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "( 100\n-\n (\n (node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=\"/home\"} expport_dashboard.sh grafana_dashboards 100)\n /\n node_filesystem_size_bytes{fstype!=\"rootfs\",mountpoint=\"/home\"}\n ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processor Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( 100 - ( (node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=\"/home\"} expport_dashboard.sh grafana_dashboards 100) / node_filesystem_size_bytes{fstype!=\"rootfs\",mountpoint=\"/home\"} ))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}